controller_manager:
  ros__parameters:
    update_rate: 1000
    # Controller types must be under controller_manager/ros__parameters to satisfy rcl parser
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    forward_command_controller:
      type: forward_command_controller/ForwardCommandController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - joint_0
    interfaces:
      - after_spring_angle
      - load_encoder_position
      - torque_estimate

forward_command_controller:
  ros__parameters:
    joints:
      - joint_0
    interface_name: target_actuator_angle
